#define BLINK termcolor::blink
#define BLUE termcolor::blue
#define BOLD termcolor::bold
#define BRIGHT_BLUE termcolor::bright_blue
#define BRIGHT_CYAN termcolor::bright_cyan
#define BRIGHT_GREEN termcolor::bright_green
#define BRIGHT_GREY termcolor::bright_grey
#define BRIGHT_MAGENTA termcolor::bright_magenta
#define BRIGHT_RED termcolor::bright_red
#define BRIGHT_WHITE termcolor::bright_white
#define BRIGHT_YELLOW termcolor::bright_yellow
#define COLOR termcolor::color
#define COLOR termcolor::color
#define COLORIZE termcolor::colorize
#define CONCEALED termcolor::concealed
#define CROSSED termcolor::crossed
#define CYAN termcolor::cyan
#define DARK termcolor::dark
#define GREEN termcolor::green
#define GREY termcolor::grey
#define IS_ATTY termcolor::is_atty
#define IS_COLORIZED termcolor::is_colorized
#define ITALIC termcolor::italic
#define MAGENTA termcolor::magenta
#define NOCOLORIZE termcolor::nocolorize
#define ON_BLUE termcolor::on_blue
#define ON_BRIGHT_BLUE termcolor::on_bright_blue
#define ON_BRIGHT_CYAN termcolor::on_bright_cyan
#define ON_BRIGHT_GREEN termcolor::on_bright_green
#define ON_BRIGHT_GREY termcolor::on_bright_grey
#define ON_BRIGHT_MAGENTA termcolor::on_bright_magenta
#define ON_BRIGHT_RED termcolor::on_bright_red
#define ON_BRIGHT_WHITE termcolor::on_bright_white
#define ON_BRIGHT_YELLOW termcolor::on_bright_yellow
#define ON_COLOR termcolor::on_color
#define ON_COLOR termcolor::on_color
#define ON_CYAN termcolor::on_cyan
#define ON_GREEN termcolor::on_green
#define ON_GREY termcolor::on_grey
#define ON_MAGENTA termcolor::on_magenta
#define ON_RED termcolor::on_red
#define ON_WHITE termcolor::on_white
#define ON_YELLOW termcolor::on_yellow
#define RED termcolor::red
#define RESET termcolor::reset
#define REVERSE termcolor::reverse
#define UNDERLINE termcolor::underline
#define WHITE termcolor::white
#define YELLOW termcolor::yellow
#define IS_ATTY termcolor::is_atty
#define IS_COLORIZED termcolor::is_colorized